Public Metadata Issuance
raphaelrobert/privacypass pull request #25
Opened 2023-11-16 22:33 UTC by cbranch

This is a variant of the Privacy Pass issuance protocol that encodes
public information that is cryptographically bound to the token but
visible to all parties (i.e. the metadata is cleartext).

The Authorisation header can receive this metadata via the extensions parameter alongside the existing token param.

A new API for issuing public tokens has been created which is extensible
in terms of the issuance protocol the client wishes to use. The basic
Privacy Pass issuance protocol is implemented in terms of this generic
implementation.

https://datatracker.ietf.org/doc/html/draft-hendrickson-privacypass-public-metadata

2023-11-20 13:16 UTC, fisherdarling commented on src/auth/authorize.rs
> +        match dbg!(key).to_lowercase().as_str() {
extra debug?

2023-11-21 11:23 UTC, raphaelrobert requested changes
Thanks for the PR! I'm not very familiar with the issuance protocol, so I flagged @chris-wood for a review as well.

I commented on a few nits for now. I see this is written so that the existing API isn't touched much. I wouldn't be against bringing the two variants of public tokens closer together on the API level. This isn't even published as a crate yet, so we still have full flexibility.

2025-03-17 07:45 UTC, raphaelrobert commented
Closing since this seems stale. Feel free to re-open if needed.

2025-03-17 07:45 UTC, closed without merging

2025-03-17 12:38 UTC, thibmeu commented
@raphaelrobert what kind of review would you expect to get it merged? this seems it would be useful, if not for 0.2.0,  for the next release

2025-03-17 12:44 UTC, raphaelrobert commented
It would be great if we could support `draft-ietf-privacypass-public-metadata-issuance`. However, I don't have the time to implement that part, and the authors of the PR seem to have abandoned it.

If someone takes ownership of this at least until it's an RFC, I'd be fine taking on the maintainership afterward.